<?php

namespace UGComponents\Profiler;

use StdClass;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Profiler_LoggerTrait_Test extends TestCase
{
  /**
   * @var LoggerTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new LoggerTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers UGComponents\Profiler\LoggerTrait::addLogger
   */
  public function testAddLogger()
  {
    $instance = $this->object->addLogger(function() {});
		$this->assertInstanceOf('UGComponents\Profiler\LoggerTraitStub', $instance);
  }

  /**
   * @covers UGComponents\Profiler\LoggerTrait::log
   */
  public function testLog()
  {
		$trigger = new StdClass();
		$trigger->success = null;
    $this->object->addLogger(function($trigger) {
			$trigger->success = true;
		})
		->log($trigger);


		$this->assertTrue($trigger->success);
  }
}

if(!class_exists('UGComponents\Profiler\LoggerTraitStub')) {
	class LoggerTraitStub
	{
		use LoggerTrait;
	}
}
