<?php

namespace UGComponents\IO\Request;

use PHPUnit\Framework\TestCase;
use UGComponents\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class IO_Request_CliTrait_Test extends TestCase
{
  /**
   * @var CliTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new CliTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * covers UGComponents\IO\Request\CliTrait::getArgs
   */
  public function testGetArgs()
  {
    $this->object->set('args', array(1, 2, 3));  
    $actual = $this->object->getArgs();
    $this->assertEquals(2, $actual[1]);
  }

  /**
   * covers UGComponents\IO\Request\CliTrait::setArgs
   */
  public function testSetArgs()
  {
    $this->object->setArgs(array(1, 2, 3));  
    $actual = $this->object->getArgs();
    $this->assertEquals(2, $actual[1]);
  }
}

if(!class_exists('UGComponents\IO\Request\CliTraitStub')) {
  class CliTraitStub extends Registry
  {
    use CliTrait;
  }
}
