<?php

namespace UGComponents\IO\Request;

use PHPUnit\Framework\TestCase;
use UGComponents\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class CookieTraitTest extends TestCase
{
  /**
   * @var CookieTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new CookieTraitStub;
    
    $this->object->set('cookie', array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * covers UGComponents\IO\Request\CookieTrait::getCookies
   */
  public function testGetCookies()
  {
    $this->assertEquals('bar', $this->object->getCookies('foo'));
  }

  /**
   * covers UGComponents\IO\Request\CookieTrait::hasCookies
   */
  public function testHasCookies()
  {
    $this->assertTrue($this->object->hasCookies('foo'));
    $this->assertFalse($this->object->hasCookies('zoo'));
  }

  /**
   * covers UGComponents\IO\Request\CookieTrait::removeCookies
   */
  public function testRemoveCookies()
  {
    $this->object->removeCookies('foo');
    $this->assertFalse($this->object->hasCookies('foo'));
  }

  /**
   * covers UGComponents\IO\Request\CookieTrait::setCookies
   */
  public function testSetCookies()
  {
    $instance = $this->object->setCookies(array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));
    
    $this->assertInstanceOf('UGComponents\IO\Request\CookieTraitStub', $instance);
		
		$instance = $this->object->setCookies('zoo');
    $this->assertInstanceOf('UGComponents\IO\Request\CookieTraitStub', $instance);

    $instance = $this->object->setCookies('zoo', 'foo', 'bar');
    $this->assertInstanceOf('UGComponents\IO\Request\CookieTraitStub', $instance);
  }
}

if(!class_exists('UGComponents\IO\Request\CookieTraitStub')) {
  class CookieTraitStub extends Registry
  {
    use CookieTrait;
  }
}
