<?php

namespace UGComponents\IO\Request;

use PHPUnit\Framework\TestCase;
use UGComponents\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class GetTraitTest extends TestCase
{
  /**
   * @var GetTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new GetTraitStub;
    
    $this->object->set('get', array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * covers UGComponents\IO\Request\GetTrait::getGet
   */
  public function testGetGet()
  {
    $this->assertEquals('bar', $this->object->getGet('foo'));
  }

  /**
   * covers UGComponents\IO\Request\GetTrait::hasGet
   */
  public function testHasGet()
  {
    $this->assertTrue($this->object->hasGet('foo'));
    $this->assertFalse($this->object->hasGet('zoo'));
  }

  /**
   * covers UGComponents\IO\Request\GetTrait::removeGet
   */
  public function testRemoveGet()
  {
    $this->object->removeGet('foo');
    $this->assertFalse($this->object->hasGet('foo'));
  }

  /**
   * covers UGComponents\IO\Request\GetTrait::setGet
   */
  public function testSetGet()
  {
    $instance = $this->object->setGet(array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));
    
    $this->assertInstanceOf('UGComponents\IO\Request\GetTraitStub', $instance);
		
		$instance = $this->object->setGet('zoo');
    $this->assertInstanceOf('UGComponents\IO\Request\GetTraitStub', $instance);

    $instance = $this->object->setGet('zoo', 'foo', 'bar');
    $this->assertInstanceOf('UGComponents\IO\Request\GetTraitStub', $instance);
  }
}

if(!class_exists('UGComponents\IO\Request\GetTraitStub')) {
  class GetTraitStub extends Registry
  {
    use GetTrait;
  }
}
