<?php

namespace UGComponents\IO\Request;

use PHPUnit\Framework\TestCase;
use UGComponents\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class PostTraitTest extends TestCase
{
  /**
   * @var PostTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new PostTraitStub;
    
    $this->object->set('post', array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * covers UGComponents\IO\Request\PostTrait::getPost
   */
  public function testGetPost()
  {  
    $this->assertEquals('bar', $this->object->getPost('foo'));
  }

  /**
   * covers UGComponents\IO\Request\PostTrait::hasPost
   */
  public function testHasPost()
  {  
    $this->assertTrue($this->object->hasPost('foo'));
    $this->assertFalse($this->object->hasPost('zoo'));
  }

  /**
   * covers UGComponents\IO\Request\PostTrait::removePost
   */
  public function testRemovePost()
  {
    $this->object->removePost('foo');
    $this->assertFalse($this->object->hasPost('foo'));
  }

  /**
   * covers UGComponents\IO\Request\PostTrait::setPost
   */
  public function testSetPost()
  {
    $instance = $this->object->setPost(array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));
    
    $this->assertInstanceOf('UGComponents\IO\Request\PostTraitStub', $instance);
		
		$instance = $this->object->setPost('zoo');
    $this->assertInstanceOf('UGComponents\IO\Request\PostTraitStub', $instance);

    $instance = $this->object->setPost('zoo', 'foo', 'bar');
    $this->assertInstanceOf('UGComponents\IO\Request\PostTraitStub', $instance);
  }
}

if(!class_exists('UGComponents\IO\Request\PostTraitStub')) {
  class PostTraitStub extends Registry
  {
    use PostTrait;
  }
}
