<?php

namespace UGComponents\IO\Request;

use PHPUnit\Framework\TestCase;
use UGComponents\Data\Registry;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:34.
 */
class IO_Request_RouteTrait_Test extends TestCase
{
  /**
   * @var RouteTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new RouteTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * covers UGComponents\IO\Request\RouteTrait::getRoute
   */
  public function testGetRoute()
  {
    $this->object->set('route', array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));

    $this->assertEquals('bar', $this->object->getRoute('foo'));
    $this->assertEquals('bar', $this->object->getRoute()['foo']);
  }

  /**
   * covers UGComponents\IO\Request\RouteTrait::getParameters
   */
  public function testGetParameters()
  {
    $this->object->set('route', array(
      'foo' => 'bar',
      'parameters' => array('foo' => 'bar')
    ));

    $this->assertEquals('bar', $this->object->getParameters('foo'));
    $this->assertEquals('bar', $this->object->getParameters()['foo']);
  }

  /**
   * covers UGComponents\IO\Request\RouteTrait::getVariables
   */
  public function testGetVariables()
  {
    $this->object->set('route', array(
      'foo' => 'bar',
      'variables' => array('foo', 'bar')
    ));

    $this->assertEquals('bar', $this->object->getVariables(1));
    $this->assertEquals('bar', $this->object->getVariables()[1]);
  }

  /**
   * covers UGComponents\IO\Request\RouteTrait::setRoute
   */
  public function testSetRoute()
  {
    $instance = $this->object->setRoute(array(
      'foo' => 'bar',
      'bar' => 'foo'
    ));

    $this->assertInstanceOf('UGComponents\IO\Request\RouteTraitStub', $instance);
  }
}

if(!class_exists('UGComponents\IO\Request\RouteTraitStub')) {
  class RouteTraitStub extends Registry
  {
    use RouteTrait;
  }
}
