<?php

namespace UGComponents\Image;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class ImageExceptionTest extends TestCase
{
  /**
   * @var ImageException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new ImageException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers UGComponents\Image\ImageException::forGDNotInstalled
   */
  public function testForGDNotInstalled()
  {
		$message = null;
		
		try {
			throw ImageException::forGDNotInstalled();
		} catch(ImageException $e) {
			$message = $e->getMessage();
		}
		
		$this->assertEquals('PHP GD Library is not installed.', $message);
  }

  /**
   * @covers UGComponents\Image\ImageException::forInvalidImageFile
   */
  public function testForInvalidImageFile()
  {
		$message = null;
		
		try {
			throw ImageException::forInvalidImageFile('foobar');
		} catch(ImageException $e) {
			$message = $e->getMessage();
		}
		
		$this->assertEquals('foobar is not a valid image file.', $message);
  }
}
