<?php

namespace UGComponents\Helper;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Helper_LoopTrait_Test extends TestCase
{
  /**
   * @var LoopTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new LoopTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * covers UGComponents\Helper\LoopTrait::loop
   */
  public function testLoop()
  {
    $self = $this;
    $this->object->loop(function($i) use ($self) {
      $self->assertInstanceOf('UGComponents\Helper\LoopTraitStub', $this);
      
      if ($i == 2) {
        return false;
      }
    });
  }
}

if(!class_exists('UGComponents\Helper\LoopTraitStub')) {
	class LoopTraitStub
	{
		use LoopTrait;
	}
}
