<?php

namespace UGComponents\Helper;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Helper_SingletonTrait_Test extends TestCase
{
  /**
   * @var SingletonTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new SingletonTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * covers UGComponents\Helper\SingletonTrait::i
   */
  public function testI()
  {
    $instance1 = SingletonTraitStub::i();
		$this->assertInstanceOf('UGComponents\Helper\SingletonTraitStub', $instance1);
		
		$instance2 = SingletonTraitStub::i();
		$this->assertTrue($instance1 === $instance2);
  }
}

if(!class_exists('UGComponents\Helper\SingletonTraitStub')) {
	class SingletonTraitStub
	{
		use SingletonTrait;
	}
}
