<?php

namespace UGComponents\IO;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:33.
 */
class IO_Middleware_Test extends TestCase
{
  /**
   * @var Middleware
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new Middleware;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers UGComponents\IO\Middleware::register
   */
  public function testRegister()
  {
    $instance = $this->object->register(function() {});
    $this->assertInstanceOf('UGComponents\IO\Middleware', $instance);
  }

  /**
   * @covers UGComponents\IO\Middleware::process
   */
  public function testProcess()
  {
    $this->assertTrue($this->object->process());
    $this->object->register(function() {
      return false;
    });

    $this->assertFalse($this->object->process());
  }
}
