<?php

namespace UGComponents\Http\Dispatcher;

use UGComponents\Resolver\ResolverTrait;
use UGComponents\Http\HttpDispatcher;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class DispatcherTraitTest extends TestCase
{
  /**
   * @var DispatcherTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new DispatcherTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * covers UGComponents\Http\DispatcherTrait::getDispatcher
   */
  public function testGetDispatcher()
  {
    $instance = $this->object->getDispatcher();
    $this->assertInstanceOf('UGComponents\Http\HttpDispatcher', $instance);
  }

  /**
   * covers UGComponents\Http\DispatcherTrait::setDispatcher
   */
  public function testSetDispatcher()
  {
    $instance = $this->object->setDispatcher(new HttpDispatcher);
    $this->assertInstanceOf('UGComponents\Http\Dispatcher\DispatcherTraitStub', $instance);
  }
}

if(!class_exists('UGComponents\Http\Dispatcher\DispatcherTraitStub')) {
  class DispatcherTraitStub
  {
    use DispatcherTrait, ResolverTrait;
  }
}
