<?php

namespace UGComponents\IO\Middleware;

use PHPUnit\Framework\TestCase;
use UGComponents\IO\Middleware;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class IO_PostProcessorTrait_Test extends TestCase
{
  /**
   * @var PostProcessorTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new PostProcessorTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * covers UGComponents\IO\PostProcessorTrait::getPostprocessor
   */
  public function testGetPostprocessor()
  {
    $instance = $this->object->getPostprocessor();
    $this->assertInstanceOf('UGComponents\IO\Middleware', $instance);
  }

  /**
   * covers UGComponents\IO\PostProcessorTrait::postprocess
   */
  public function testPostprocess()
  {
    $instance = $this->object->postprocess(function() {});
    $this->assertInstanceOf('UGComponents\IO\Middleware\PostProcessorTraitStub', $instance);
  }

  /**
   * covers UGComponents\IO\PostProcessorTrait::setPostprocessor
   */
  public function testSetPostprocessor()
  {
    $instance = $this->object->setPostprocessor(new Middleware);
    $this->assertInstanceOf('UGComponents\IO\Middleware\PostProcessorTraitStub', $instance);
  }
}

if(!class_exists('UGComponents\IO\PostProcessorTraitStub')) {
  class PostProcessorTraitStub
  {
    use PostProcessorTrait;
  }
}
